version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports: 
      - '$PORT:$PORT'
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    volumes:
      - $HOME/volumes/postgres/pismo-transactions:/data/postgres/pismo-transactions:rw%